// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf2V4dQscUJoq2aTZyKqmcgWAAmv1rFqA',
    appId: '1:419608757359:web:955a6e2ee5a00cfe74b99a',
    messagingSenderId: '419608757359',
    projectId: 'senn-2f0ea',
    authDomain: 'senn-2f0ea.firebaseapp.com',
    storageBucket: 'senn-2f0ea.firebasestorage.app',
    measurementId: 'G-2DQ4HX3XS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi2hqa2MNetOSNEPEFq7YY-K6AU-ACqlo',
    appId: '1:419608757359:android:135d10d0e1c0845174b99a',
    messagingSenderId: '419608757359',
    projectId: 'senn-2f0ea',
    storageBucket: 'senn-2f0ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZAP4z7LdUwxAaIO79hfz7pmFi_DcrzXM',
    appId: '1:419608757359:ios:ea3aa46d09b305d974b99a',
    messagingSenderId: '419608757359',
    projectId: 'senn-2f0ea',
    storageBucket: 'senn-2f0ea.firebasestorage.app',
    iosBundleId: 'com.example.dentalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZAP4z7LdUwxAaIO79hfz7pmFi_DcrzXM',
    appId: '1:419608757359:ios:ea3aa46d09b305d974b99a',
    messagingSenderId: '419608757359',
    projectId: 'senn-2f0ea',
    storageBucket: 'senn-2f0ea.firebasestorage.app',
    iosBundleId: 'com.example.dentalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf2V4dQscUJoq2aTZyKqmcgWAAmv1rFqA',
    appId: '1:419608757359:web:ff04a86b5a56162b74b99a',
    messagingSenderId: '419608757359',
    projectId: 'senn-2f0ea',
    authDomain: 'senn-2f0ea.firebaseapp.com',
    storageBucket: 'senn-2f0ea.firebasestorage.app',
    measurementId: 'G-SS35VB7TVF',
  );
}
